### PR TITLE
Update Jenkins_Notes.txt

### PR DESCRIPTION
**Pull request by ankmraobade**
best practice on above tools

### CODE REVIEW

**Review by ssrini27 — CHANGES_REQUESTED** [review]
Hi Ankam,
If possible, please add jenkins related points...

**Comment by ankmraobade** [comment]
i will try
give me some time

**Comment by ssrini27** [comment]
Nice Ankam.  We look forward your valuable points...

**Comment by ankmraobade** [comment]
ok good

**Pull request closed without merging**
